apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  guestbook/enabled: "true"
          - plugin:
              configMapRef:
                name: values-pipeline-plugin
              requeueAfterSeconds: 300
              input:
                parameters:
                  name: "{{ .name }}"
                  server: "{{ .server }}"
                  context:
                    cluster:
                      name: "{{ .name }}"
                      nameNormalized: "{{ .nameNormalized }}"
                  emit:
                    appName: guestbook
                    namespace: guestbook
                    repoURL: https://github.com/argoproj/argocd-example-apps.git
                    targetRevision: master
                    path: helm-guestbook
                  defaults:
                    domain: aerxd.tech
                    host: "{{ .appName }}.{{ .name }}.{{ .domain }}"
                    replicaCount: 1
                  selectorOverrides:
                    - path: name
                      overrides:
                        dev-processing:
                          domain: blabla.com
  template:
    metadata:
      name: "{{ .appName }}-{{ .name }}"
    spec:
      project: default
      destination:
        server: "{{ .server }}"
        namespace: "{{ .namespace }}"
      source:
        repoURL: "{{ .repoURL }}"
        targetRevision: "{{ .targetRevision }}"
        path: "{{ .path }}"
        helm:
          values: |
            {{- .resolvedValuesYaml | nindent 12 }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
