apiVersion: v1
kind: ConfigMap
metadata:
  name: values-pipeline-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/name: values-pipeline-plugin
    app.kubernetes.io/part-of: argocd
data:
  baseUrl: http://values-pipeline-plugin.argocd.svc.cluster.local
  requestTimeout: "60"
  token: $plugin.values-pipeline-plugin.token
