apiVersion: v1
kind: Secret
metadata:
  name: values-pipeline-plugin-token
  namespace: argocd
  labels:
    app.kubernetes.io/name: values-pipeline-plugin
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  token: change-me
