apiVersion: v1
kind: Secret
metadata:
  name: argocd-appset-params-template-plugin-token
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-appset-params-template-plugin
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  token: change-me
