apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-appset-params-template-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-appset-params-template-plugin
    app.kubernetes.io/part-of: argocd
automountServiceAccountToken: false
